config/routes.rb
Rails.application.routes.draw do

  root'pages#home'


  devise_for 	:users,
  				path: '',
  				path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  				controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'pricing'
      get 'amenities'
      get 'location'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :acommodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true

  def cover_photo(size)
    if self.photos.length > 0
      self.photos[0].image.url(size)
    else
      "blank.jpg"
    end
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable

         validates :fullname, presence: true, length: {maximum: 50}
         has_many :rooms
         has_many :reservations


    def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
    	return user
	    else

	  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.fullname = auth.info.name
	    user.image = auth.info.image
	    user.uid = auth.uid
	    user.provider = auth.provider
	    # If you are using confirmable and the provider(s) you use validate emails,
	    # uncomment the line below to skip the confirmation emails.
	    user.skip_confirmation!
		end

  	end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
		devise_parameter_sanitizer.permit(:account_update, keys: [:fullname,:phone_number, :description])

	end


end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController


  def create
    @room = Room.find(params[:room_id])

   if params[:images]
     params[:images].each do |img|
       @room.photos.create(image: img)
     end

     @photos = @room.photos
     redirect_back(fallback_location: request.referer, notice: "Saved...")
   end



  end
  def destroy
    @photo = Photo.find(params[:id])
    room = @photo.room

    @photo.destroy
    @photos = Photo.where(room_id: room.id)

    respond_to :js
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
    def update_resource(resource, params)
      resource.update_without_password(params)
    end
end

app/controllers/room_controller.rb
class RoomController < ApplicationController

  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved..."
    else
      render :new, notice: "Something went wrong while saving..."
  end

  def show

  end

  def listing

  end

  def pricing

  end

  def description

  end

  def photo_upload
  end

  def amenities
  end

  def location
  end

  def update
    if @room.update(room_params)
      flash[:notice] = "Saved"
    else
      flash[:notice] = "Something went wrong, nobody new why..."
    end
    redirect_back(fallback_location: request.referer)
  end

  private
  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:home_type, :room_type, :acommodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air, :is_heating :is_internet, :price, :active)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorised, only: [:listing, :pricing, :description, :photo_upload, :amenities, :location, :update]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved..."
    else
      flash[:alert] = "Something went wrong..."
      render :new
    end
  end



  def show
    @photos = @room.photos

  end

  def listing

  end

  def pricing

  end

  def description

  end

  def photo_upload
    @photos = @room.photos
  end

  def amenities
  end

  def location
  end

  def update
    if @room.update(room_params)
      flash[:notice] = "Saved"
    else
      flash[:notice] = "Something went wrong, nobody new why..."
    end
    redirect_back(fallback_location: request.referer)
  end

  private
  def set_room
    @room = Room.find(params[:id])
  end

  def is_authorised
    redirect_to root_path, alert: "You don't have permission" unless current_user.id == @room.user_id
  end

  def room_params
      params.require(:room).permit(:home_type, :room_type, :acommodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air, :is_heating, :is_internet, :price, :active)
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :authenticate_user!, only: [:show]


  def show
    @user = User.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

	# def avatar_url(user)
	# 	gravatar_id = Digest::MD5::hexdigest(user.email).downcase
	# 	"http://www.gravatar.com/avatar/#{gravatar_id}.JPEG?d=identical&s=150"
	# end

	
	def avatar_url(user)
	
	if user.image
		"http://graph.facebook.com/#{user.uid}/picture?type=large"
	else
	gravatar_id = Digest::MD5::hexdigest(user.email).downcase
	"http://gravatar.com/avatar/#{gravatar_id}.jpg?d=identicon&s=150 "

	end

	end
 
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirPikachu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>

  <body>

        <%= render 'shared/navbar'%>
        <%= render 'shared/message'%>





        <div class="container">
        <%= yield %>
        </div>


  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
<br></br>

<div class="row">
   <% @photos.each do |photo| %>
     <div class="col-md-4">
       <div class="panel panel-default">
         <div class="panel-heading2 preview">
           <%= image_tag photo.image.url() %>
         </div>
         <div class="panel-body">
           <span class="pull-right">
              <%= link_to room_photo_path(photo.room_id, photo), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
              <% end %>


            </span>
         </div>
  </div>
</div>
<% end %>

</div>




<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos_list' %>")

app/views/rooms/_room_menu.html.erb
<ul class="sidebar-list">

  <li class="sidebar-item">
  <%= link_to "Listing",listing_room_path, class: "sidebar-link active" %>
  <span class="pull-right text-babu" ><i class="fa fa-check"></i></span>
  <li class="sidebar-item text-babu">
  <%= link_to "Pricing",pricing_room_path, class: "sidebar-link active" %>
  <% if !@room.price.blank? %>
  <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  <% end %>
  </li>
  <li class="sidebar-item ">
  <%= link_to "Description",description_room_path, class: "sidebar-link active" %>
  <% if !@room.listing_name.blank? %>
  <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  <% end %>
  </li>
  <li class="sidebar-item ">
  <%= link_to "Photos",photo_upload_room_path, class: "sidebar-link active" %>
  <% if !@room.photos.blank? %>
  <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  <% end %>
  </li>
  <li class="sidebar-item ">
  <%= link_to "Amenities",amenities_room_path, class: "sidebar-link active" %>
  <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item ">
  <%= link_to "Location",location_room_path, class: "sidebar-link active" %>
  <% if !@room.address.blank? %>
  <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  <% end %>
  </li>
</ul>

<hr/>
<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>

<%= form_for @room do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>

app/views/rooms/amenities.html.erb
<div class="row">
  <div class="col-md-3">
    <%=render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Ammenities
      </div>
      <br/>
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>
          <div class="row form-group">
            <div class="col-md-4">
              <%= f.check_box :is_tv %> TV
            </div>

            <div class="col-md-4">
              <%= f.check_box :is_kitchen %> Kitchen
            </div>

            <div class="col-md-4">
              <%= f.check_box :is_internet %> Internet
            </div>
          </div>

            <div class="row form-group">
              <div class="col-md-4">
                <%= f.check_box :is_heating %> Heating
              </div>

              <div class="col-md-4">
                <%= f.check_box :is_air %> AirCon
              </div>
            </div>
          <br/>

          <div class="text-center">
            <%= f.submit "Save", class: "btn btn-form" %>
          </div>


          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p>

app/views/rooms/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Description
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label>Listing name</label>
                <%= f.text_field :listing_name, placeholder: "What is your listing name?", class: "form-control", required: true %>
              </div>
            </div>

            <div class="row">
              <div class="form-group">
                <label>Summary</label>
                <%= f.text_area :summary, rows: 5, placeholder: "Summary of your house", class: "form-control", required: true %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item">
        <%= link_to "Your Listings", rooms_path, class: "sidbar-link active"%>
      </li>
      <li>  <%= link_to "Your Reservations", rooms_path, class: "sidbar-link active"%></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading"> LISTINGS

      </div>
      <div class="panel-body">
        <% @rooms.each do |room| %>
        <div class="row">
          <div class="col-md-2">
             <%= image_tag room.cover_photo(:thumb) %>
          </div>
          <div class="col-md-7">
            <h4><%= room.listing_name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "Update", listing_room_path(room), class: "btn btn-form"%>

          </div>

        </div>
        <hr/>

        <% end %>

      </div>

    </div>

  </div>

</div>

app/views/rooms/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Listing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Home Type</label>
                  <%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                                id: "home_type", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Room Type</label>
                  <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                                id: "room_type", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Accommodate</label>
                  <%= f.select :acommodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                id: "accommodate", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Bedrooms</label>
                  <%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                id: "bed_room", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label>Bathrooms</label>
                  <%= f.select :bath_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                id: "bath_rooms", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

            </div>

            <div><%= f.submit "Save", class: "btn btn-normal" %></div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%=render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Location
      </div>
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label> Address</label>
                <%= f.text_field :address, placeholder: "What is your address", class: "form-control"%>
              </div>
            </div>
            <div class="text-center">
              <%=f.submit "save", class: "btn btn-form" %>
            </div>

          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create your beautiful place
  </div>
  <div class="panel-body">
    <div class="container">

      <%= form_for @room do |f| %>

        <div class="row">

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Home Type</label>
              <%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                            id: "home_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Room Type</label>
              <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                            id: "room_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Acommodate</label>
              <%= f.select :acommodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                            id: "acommodate", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bedrooms</label>
              <%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                            id: "bed_room", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bathrooms</label>
              <%= f.select :bath_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                            id: "bath_rooms", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

        </div>

        <div><%= f.submit "Create My Room", class: "btn btn-normal" %></div>

      <% end %>

    </div>
  </div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%=render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Photos
      </div>
      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!-- Photo upload-->

              <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
              <div class="row">
                <div class="form-group">
                  <span class="btn btn-default btn-file text-babu">
                    <i class="fa fa-cloud-upload" aria-hidden="true"></i> Select Photos
                    <%= file_field_tag "images[]", type: :file, multipart:true %>

                  </span>
                </div>
              </div>
              <div class="text-center">
                <%= f.submit " Add Photos", class: "btn btn-form"%>
              </div>

              <% end %>


            </div>
          </div>
          <div id="photos"><%= render 'photos/photos_list'%></div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%=render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Pricing
      </div>
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label> Price</label>
                <%= f.text_field :price, placeholder: "eg: $ 100", class: "form-control"%>
              </div>
            </div>
            <div class="text-center">
              <%=f.submit "save", class: "btn btn-form" %>
            </div>

          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<!--image-->
<div class="row">
  <div class="col-md-12">
    <%= image_tag @room.cover_photo(nil), width: "100%" %>

  </div>
</div>
<br/>

<div class="row">
  <!-- LEFT PANEL -->
  <div class="col-md-8">

    <!-- Listing Name -->
    <div class="row">
      <div class="col-md-8">
        <h1><%= @room.listing_name %></h1>
        <%= @room.address %>

      </div>
      <div class="col-md-4 text-center">
        <%= image_tag avatar_url(@room.user), class: "img-circle avatar-large"%><br/><br/>
        <%= @room.user.fullname %>

      </div>

    </div>
    <hr/>


    <!-- Room info -->
    <div class="row text-babu">
      <div class="row text-center row-space-1">
        <div class="row col-md-3">
          <i class="fa fa-home fa-2x"></i>
        </div>
        <div class="row col-md-3">
          <i class="fa fa-user-circle-o fa-2x"></i>
        </div>
        <div class="row col-md-3">
          <i class="fa fa-bed fa-2x"></i>
        </div>
        <div class="row col-md-3">
          <i class="fa fa-bath fa-2x"></i>
        </div>
      </div>
      <div class="row text-center">
        <div class="col-md-3"><%= @room.home_type%></div>
        <div class="col-md-3"><%= pluralize(@room.acommodate,"Guest")%></div>
        <div class="col-md-3"><%= pluralize(@room.bed_room,"Bedroom")%></div>
        <div class="col-md-3"><%= pluralize(@room.bath_room,"Bathroom")%></div>

      </div>

    </div>
    <hr/>

    <!-- About -->
    <div class="row">
      <div class="col-md-12">
        <h3>About This Listing</h3>
        <p><%= @room.summary %></p>
      </div>

    </div>
    <hr/>

    <!-- Amenities -->
    <div class="row">
      <div class="col-md-3">
        <h4>Ammenities</h4>
      </div>
      <div class="col-md-9">
        <div class="row">
          <div class="col-md-6">
            <ul class="amenities">
                    <li class="<%= 'text-line-through' if !@room.is_tv %>">TV</li>
                    <li class="<%= 'text-line-through' if !@room.is_kitchen %>">Kitchen</li>
                    <li class="<%= 'text-line-through' if !@room.is_internet %>">Internet</li>
                  </ul>
                </div>
                <div class="col-md-6">
                  <ul class="amenities">
                    <li class="<%= 'text-line-through' if !@room.is_heating %>">Heating</li>
                    <li class="<%= 'text-line-through' if !@room.is_air %>">Air Conditioning</li>
                  </ul>
          </div>
        </div>

      </div>

    </div>
    <hr/>

    <!-- Carousel -->
    <div class="row">

      <% if @photos.length > 0 %>
          <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <% @photos.each do |photo| %>
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
            <% end %>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <% @photos.each do |photo| %>
                <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= image_tag photo.image.url() %>
                </div>
            <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% end %>

    </div>
    <hr/>
  <!-- RIGHT PANEL -->
  <div class="col-md-4">
  <!-- Reservation forms -->

  </div>
</div>

app/views/rooms/update.html.erb
<h1>Room#update</h1>
<p>Find me in app/views/room/update.html.erb</p>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty?  %>
<script type="text/javascript">
	<% resource.errors.full_messages.each do |value|%>
	
	toastr.error('<%= value %>')
	<% end %>
</script>

<%end%>

app/views/shared/_message.html.erb
<%unless flash.empty?  %>
<script type="text/javascript">
	<% flash.each do |key, value|%>
	<% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
	toastr['<%= type %>']('<%= value %>')
	<% end %>
	

</script>

<%end%>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">My KLON BnB </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">

            <% if (!user_signed_in?) %>

              <li><%= link_to "login", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>

            <% else %>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

                <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;


              <%= current_user.fullname %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Manage listing</a></li>
                <li><a href="#">List Your Space</a></li>
                <li><a href="#">Your Reservations</a></li>
                <li><a href="#">Your Trips</a></li>
                <li role="separator" class="divider"></li>

                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>

            <% end %>

          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/users/show.html 2.erb
<div class="row">
<div class="col-md-3">
  <div class="center">
  <%= image_tag avatar_url(@user), class: "avatar-full" %>

  </div>
  <div class="panel panel-default">
    <div class="panel-heading">Verification</div>
    <div class="panel-body">
      Email Address <br/>
      Phone number <br/>
    </div>
  </div>
</div>


<div class="col-md-9">
  <h2><%= @user.fullname %></h2>
  <div class="description row-space-3"></div>
  <%= @user.description %>
</div>

</div>

app/views/users/show.html.erb
<div class="row">
<div class="col-md-3">
  <div class="center">
  <%= image_tag avatar_url(@user), class: "avatar-full" %>

  </div>
  <div class="panel panel-default">
    <div class="panel-heading">Verification</div>
    <div class="panel-body">
      Email Address <br/>
      Phone number <br/>
    </div>
  </div>
</div>


<div class="col-md-9">
  <h2><%= @user.fullname %></h2>
  <div class="description row-space-3"></div>
  <%= @user.description %>
</div>

</div>